host: den-dev-vm24

services:
  classifier:
    port: 8140

  search:
    port: 8220

  pricing:
    port: 8180

  providerdirectory:
    port: 8160

  guidetool:
    port: 8240

  benefits:
    port: 8260

  account:
    port: 8280

  recommendations:
    port: 8280

  events:
    port: 8460

  configurator:
    port: 8380

  pastcare:
    port: 8420

  rewards:
    port: 8520

  drug:
    port: 8540

  content:
    port: 8560

  providerdetail:
    port: 8600

  email:
    port: 8640

  reviews:
    port: 8680

  coe:
    port: 8720

  proxy:
    port: 8300

ops:
  evaluate_expression:
  add_method_logger:
  add_method_timer:
  restore_class:
